### ISSUE TITLE
une option "token" 

### ISSUE THREAD

**Issue by yann-yinn** [fabienjuif/graph-client#4]
Hello !
Suggestion à l'arrache pour la DX : une simple clef "token" dans la création du client, a qui on peut passer une fonction qui retourne (ou pas) un token pour qu'il puisse être ajouté à chaque requête ?

Il y a un client GraphQL super simple qui s'appelle `graphql-request` que j'aime bien, mais la dernière fois que je m'en suis servi, il ne gérait pas les tokens sans bidouille, alors que je me retrouve presque systématiquement à gérer de authent' en JWT

**Comment by fabienjuif** [comment]
est-ce que le fait de passer des options fetch dans le createClient t'irait ?
exemple d'api:
```js
import createClient from '@fabienjuif/graph-client'

const graphql = createClient({
  url,
  cache,
  logger,
  headers: {
    authorization: 'Bearer my-token',
  },
})
```

**Comment by fabienjuif** [comment]
Et je peux ajouter un truc du genre:
```js
graphql.setHeaders({
  authorization: 'Bearer my-token',
})
```

pour que ce soit dynamique

**Comment by yann-yinn** [comment]
J'imaginais plutôt :
```
const graphql = createClient({
  url,
  cache,
  logger,
  token: getToken()
})
```
car il faut forcément mettre dans un header `Bearer truc` si la fonction renvoie un token

**Comment by fabienjuif** [comment]
Je pense que ça dépend de l'implémentation de l'API, même si c'est un standard tu peux avoir des écarts j'imagine.

**Comment by fabienjuif** [comment]
La second implementation que je propose ne ferait pas l'affaire ?

**Comment by yann-yinn** [comment]
Oui et non, ma proposition consiste à automatiser:  appeler le callback token automatiquement à chaque requête envoyée, et à mettre ou pas le header si la fonction renvoie `null` ou `false`. Les headers manuel, mais il faut le setter de manière évenementiel à chaque requête en fonction de la présence ou pas du token. 

ça donne le boilerplate suivant en apollo ( exemple fictif pris sur leur doc)

```js
const authLink = setContext((_, { headers }) => {
  // get the authentication token from local storage if it exists
  const token = localStorage.getItem('token');
  // return the headers to the context so httpLink can read them
  return {
    headers: {
      ...headers,
      authorization: token ? `Bearer ${token}` : "",
    }
  }
});

const client = new ApolloClient({
  link: authLink.concat(httpLink),
  cache: new InMemoryCache()
});
```

**Comment by yann-yinn** [comment]
C'est jutstement cette partie "setContext" qui est automatisable puisqu'il faut toujours faire la même chose : appeler le token à chaque requête, si il est pas expiré ajouter un header.

C'est une proposition haut niveau, c'est juste un besoin de base avec JWT qui est mal couvert avec les autres librairies je trouve; tu en fais ce que tu veux :)

**Comment by fabienjuif** [comment]
Yes je vais y réfléchir, cette lib je voulais qu'elle soit bas niveau (pour ça que tu fournis le fetch / le cache).
Mais pour que ça coute d'ajouter ta proposition... ça se tient !

Tu veux essayer de faire la PR peut être ?

**Comment by yann-yinn** [comment]
Ca serait avec plaisir car je suis pas satisfait des clients existants pour des besoins simples, (graphql-request gère pas les tokens sauf à recréer le client à chaque requête, apollo-client est complet mais tordu et doc confuse) mais j'ai d'autres prios pour le moment :)

En effet je trouve que ton approche est très bonne et simple, j'aime beaucoup ! ( d'où l'idée de simplifier aussi le code nécessaire pour token JWT d'ailleurs, comme ça en deux lignes tu as un client GraphQL avec authorization JWT, record du monde :-p )

**Comment by fabienjuif** [comment]
Juste pour être sur qu'on se comprenne, j'ai eu un doute en relisant tes précédents commentaire.
Avec la second implémentation que je propose, celle ci:

Tu me répond
> Le header manuel ça marche très bien, mais il faut le setter de manière évenementiel à chaque requête en fonction de la présence ou pas du token.

Mais avec cette implémentation tu ferais le "setHeaders" qu'une fois -> au moment où tu as le token
Apres toutes les requêtes l'utiliseraient.
Et si l'utilisateur se déconnecte, alors tu feras `graphql.setHeaders({ authorization: undefined })` et toutes les requêtes suivantes seront sans le token.

Ca répond pas à ce que tu voudrais/imaginais ?

**Comment by yann-yinn** [comment]
@fabienjuif en effet, après, il faut manuellement remettre le setHeaders à undefined,  quand l'utilisateur se déconnecte, mais aussi quand le token n'est plus valide et ça fonctionne. C'est juste un raccourci puisqu'au fond, si le token est valide, je veux authentifier ma requête, sinon non. Mais tu as raison sur le côté standard, je sais pas si le fait de mettre un header "authorization: Bearer xxx" est juste une bonne pratique ou si c'est spécifié quelque part pour JWT, peut être que le nommer "token" n'est pas adapté. BearerToken ? AuthorizationBearerToken ?

**Comment by fabienjuif** [comment]
J'ai ajouté l'option, je verrais bien comment ça vie :)
